server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bear
    username: root
    password: 89757
#    type: com.alibaba.druid.pool.DruidDataSource

bear:
  path: E:\IT Career\Java World\bear_take_out\\img\\

mybatis-plus:
  global-config:
    db-config:
      id-type: auto


logging:
  level:
    root: debug
    com.baomidou.mybatisplus.mapper: debug
  console:
    enabled: true

